services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: eliminator
      POSTGRES_PASSWORD: eliminator
      POSTGRES_DB: eliminator
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/db:ro,Z
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro,Z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eliminator -d eliminator"]
      interval: 3s
      timeout: 3s
      retries: 20

  api:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://eliminator:eliminator@db:5432/eliminator
    volumes:
      - ./backend/app:/app/app:ro,Z

    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  web:
    image: nginx:alpine
    depends_on:
      - api
    ports:
      - "8080:80"
    volumes:
    - ./frontend:/usr/share/nginx/html:ro,Z
    - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro,Z

volumes:
  pgdata:

